import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  API_PORT: Joi.number().default(3000),
  JWT_SECRET: Joi.string().min(8).default('change-me'),
  JWT_EXPIRES_IN: Joi.string().default('7d'),
  STORAGE_ROOT: Joi.string().default('./storage'),
  MAX_UPLOAD_MB: Joi.number().integer().positive().default(50),
  DATABASE_PROVIDER: Joi.string().valid('postgresql', 'sqlite').default('postgresql'),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  GPU_LEASE_TTL_MS: Joi.number().integer().min(15000).default(180000),
  GPU_LEASE_POLL_MS: Joi.number().integer().min(100).default(1000),
  ENABLE_OLLAMA: Joi.boolean().truthy('true').falsy('false').default(false),
  OLLAMA_BASE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).default('http://localhost:11434'),
  OLLAMA_MODEL: Joi.string().default('qwen3:8b'),
  OLLAMA_TIMEOUT_MS: Joi.number().integer().positive().default(600000),
  OLLAMA_KEEP_ALIVE: Joi.string().default('0s'),
  OLLAMA_THINK: Joi.boolean().truthy('true').falsy('false').default(false),
  SCENE_VISUAL_PROVIDER: Joi.string().valid('procedural', 'comfyui').default('procedural'),
  COMFYUI_BASE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).default('http://localhost:8188'),
  COMFYUI_HEALTH_TIMEOUT_MS: Joi.number().integer().positive().default(5000),
  COMFYUI_CHECKPOINT_NAME: Joi.string().allow('').default(''),
  COMFYUI_STORYBOARD_WIDTH: Joi.number().integer().positive().default(1536),
  COMFYUI_STORYBOARD_HEIGHT: Joi.number().integer().positive().default(864),
  COMFYUI_STORYBOARD_STEPS: Joi.number().integer().positive().default(24),
  COMFYUI_STORYBOARD_CFG: Joi.number().positive().default(5),
  COMFYUI_STORYBOARD_SAMPLER: Joi.string().default('uni_pc'),
  COMFYUI_STORYBOARD_SCHEDULER: Joi.string().default('simple'),
  SNAPGEN_API_KEY: Joi.string().allow('').default(''),
  DATABASE_URL: Joi.string().default('postgresql://postgres:postgres@localhost:5432/video_saas')
});
