import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  STORAGE_ROOT: Joi.string().default('./storage'),
  FFMPEG_PATH: Joi.string().default('ffmpeg'),
  FFPROBE_PATH: Joi.string().default('ffprobe'),
  MOCK_AUDIO_DURATION_SECONDS: Joi.number().positive().default(30),
  ENABLE_WHISPER: Joi.boolean().truthy('true').falsy('false').default(false),
  WHISPER_PYTHON_PATH: Joi.string().default('python'),
  WHISPER_MODEL: Joi.string().default('distil-large-v3'),
  WHISPER_DEVICE: Joi.string().valid('cpu', 'cuda').default('cuda'),
  WHISPER_COMPUTE_TYPE: Joi.string().default('float16'),
  WHISPER_FALLBACK_DEVICE: Joi.string().valid('cpu', 'cuda').default('cpu'),
  WHISPER_FALLBACK_COMPUTE_TYPE: Joi.string().default('int8'),
  WHISPER_TIMEOUT_MS: Joi.number().integer().positive().default(600000),
  WHISPER_LANGUAGE: Joi.string().allow('').default(''),
  WHISPER_EXTRA_PATHS: Joi.string().allow('').default(''),
  RENDER_WIDTH: Joi.number().integer().positive().default(1280),
  RENDER_HEIGHT: Joi.number().integer().positive().default(720),
  RENDER_FRAME_RATE: Joi.number().integer().positive().default(24),
  RIFE_EXECUTABLE_PATH: Joi.string().default('./tools/rife-ncnn-vulkan/rife-ncnn-vulkan.exe'),
  RIFE_MODEL_PATH: Joi.string().default('./tools/rife-ncnn-vulkan/rife-v4.6'),
  RIFE_GPU_ID: Joi.number().integer().min(-1).default(0),
  RIFE_CRF: Joi.number().integer().min(0).max(51).default(17),
  RIFE_FFMPEG_PRESET: Joi.string().default('slow'),
  ENABLE_OLLAMA: Joi.boolean().truthy('true').falsy('false').default(false),
  OLLAMA_BASE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).default('http://localhost:11434'),
  OLLAMA_MODEL: Joi.string().default('qwen3:8b'),
  OLLAMA_TIMEOUT_MS: Joi.number().integer().positive().default(180000),
  OLLAMA_KEEP_ALIVE: Joi.string().default('0s'),
  OLLAMA_THINK: Joi.boolean().truthy('true').falsy('false').default(false),
  SCENE_VISUAL_PROVIDER: Joi.string().valid('procedural', 'comfyui').default('procedural'),
  COMFYUI_BASE_URL: Joi.string()
    .uri({ scheme: ['http', 'https'] })
    .default('http://localhost:8188'),
  COMFYUI_OUTPUT_HOST_PATH: Joi.string().default('./storage/comfyui/output'),
  COMFYUI_TIMEOUT_MS: Joi.number().integer().positive().default(1200000),
  COMFYUI_POLL_INTERVAL_MS: Joi.number().integer().positive().default(3000),
  COMFYUI_VIDEO_WORKFLOW_NAME: Joi.string().default('wan-2.2-ti2v-5b'),
  COMFYUI_ENABLE_IMAGE_FALLBACK: Joi.boolean().truthy('true').falsy('false').default(false),
  COMFYUI_CHECKPOINT_NAME: Joi.string().allow('').default(''),
  COMFYUI_VIDEO_UNET_NAME: Joi.string().default('wan2.2_ti2v_5B_fp16.safetensors'),
  COMFYUI_VIDEO_CLIP_NAME: Joi.string().default('umt5_xxl_fp8_e4m3fn_scaled.safetensors'),
  COMFYUI_VIDEO_CLIP_TYPE: Joi.string().default('wan'),
  COMFYUI_VIDEO_VAE_NAME: Joi.string().default('wan2.2_vae.safetensors'),
  COMFYUI_VIDEO_MODEL_SHIFT: Joi.number().positive().default(8),
  COMFYUI_VIDEO_FPS: Joi.number().integer().valid(16, 24).default(16),
  COMFYUI_WIDTH: Joi.number().integer().positive().default(1024),
  COMFYUI_HEIGHT: Joi.number().integer().positive().default(576),
  COMFYUI_STEPS: Joi.number().integer().positive().default(20),
  COMFYUI_CFG: Joi.number().positive().default(5),
  COMFYUI_SAMPLER: Joi.string().default('uni_pc'),
  COMFYUI_SCHEDULER: Joi.string().default('simple'),
  CHILDREN_CLIP_CHARACTER_CHECKPOINT_NAME: Joi.string().allow('').default(''),
  CHILDREN_CLIP_CHARACTER_WIDTH: Joi.number().integer().positive().default(1024),
  CHILDREN_CLIP_CHARACTER_HEIGHT: Joi.number().integer().positive().default(1024),
  CHILDREN_CLIP_CHARACTER_STEPS: Joi.number().integer().positive().default(30),
  CHILDREN_CLIP_CHARACTER_CFG: Joi.number().positive().default(6.5),
  CHILDREN_CLIP_CHARACTER_SAMPLER: Joi.string().default('dpmpp_2m'),
  CHILDREN_CLIP_CHARACTER_SCHEDULER: Joi.string().default('karras'),
  CHILDREN_CLIP_CHARACTER_LORA_NAME: Joi.string().allow('').default(''),
  CHILDREN_CLIP_CHARACTER_LORA_STRENGTH: Joi.number().min(-3).max(3).default(1),
  ENABLE_AI_FALLBACKS: Joi.boolean().truthy('true').falsy('false').default(true),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  WORKER_LOCK_DURATION_MS: Joi.number().integer().positive().default(1800000),
  WORKER_STALLED_INTERVAL_MS: Joi.number().integer().positive().default(30000),
  DATABASE_URL: Joi.string().default('postgresql://postgres:postgres@localhost:5432/video_saas')
});
