import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  STORAGE_ROOT: Joi.string().default('./storage'),
  FFMPEG_PATH: Joi.string().default('ffmpeg'),
  FFPROBE_PATH: Joi.string().default('ffprobe'),
  MOCK_AUDIO_DURATION_SECONDS: Joi.number().positive().default(30),
  ENABLE_WHISPER: Joi.boolean().truthy('true').falsy('false').default(false),
  WHISPER_PYTHON_PATH: Joi.string().default('python'),
  WHISPER_MODEL: Joi.string().default('distil-large-v3'),
  WHISPER_DEVICE: Joi.string().valid('cpu', 'cuda').default('cuda'),
  WHISPER_COMPUTE_TYPE: Joi.string().default('float16'),
  WHISPER_TIMEOUT_MS: Joi.number().integer().positive().default(600000),
  WHISPER_LANGUAGE: Joi.string().allow('').default(''),
  RENDER_WIDTH: Joi.number().integer().positive().default(1280),
  RENDER_HEIGHT: Joi.number().integer().positive().default(720),
  RENDER_FRAME_RATE: Joi.number().integer().positive().default(24),
  ENABLE_OLLAMA: Joi.boolean().truthy('true').falsy('false').default(false),
  OLLAMA_BASE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).default('http://localhost:11434'),
  OLLAMA_MODEL: Joi.string().default('qwen3:8b'),
  OLLAMA_TIMEOUT_MS: Joi.number().integer().positive().default(180000),
  SCENE_VISUAL_PROVIDER: Joi.string().valid('procedural', 'comfyui').default('procedural'),
  COMFYUI_BASE_URL: Joi.string()
    .uri({ scheme: ['http', 'https'] })
    .default('http://localhost:8188'),
  COMFYUI_OUTPUT_HOST_PATH: Joi.string().default('./storage/comfyui/output'),
  COMFYUI_TIMEOUT_MS: Joi.number().integer().positive().default(300000),
  COMFYUI_POLL_INTERVAL_MS: Joi.number().integer().positive().default(3000),
  COMFYUI_CHECKPOINT_NAME: Joi.string().default('sd_xl_turbo_1.0.safetensors'),
  COMFYUI_VIDEO_UNET_NAME: Joi.string().default('wan2.2_ti2v_5B_fp16.safetensors'),
  COMFYUI_VIDEO_CLIP_NAME: Joi.string().default('umt5_xxl_fp8_e4m3fn_scaled.safetensors'),
  COMFYUI_VIDEO_CLIP_TYPE: Joi.string().default('wan'),
  COMFYUI_VIDEO_VAE_NAME: Joi.string().default('wan2.2_vae.safetensors'),
  COMFYUI_VIDEO_MODEL_SHIFT: Joi.number().positive().default(8),
  COMFYUI_VIDEO_FPS: Joi.number().integer().positive().default(24),
  COMFYUI_WIDTH: Joi.number().integer().positive().default(1024),
  COMFYUI_HEIGHT: Joi.number().integer().positive().default(576),
  COMFYUI_STEPS: Joi.number().integer().positive().default(20),
  COMFYUI_CFG: Joi.number().positive().default(5),
  COMFYUI_SAMPLER: Joi.string().default('uni_pc'),
  COMFYUI_SCHEDULER: Joi.string().default('simple'),
  ENABLE_AI_FALLBACKS: Joi.boolean().truthy('true').falsy('false').default(true),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  DATABASE_URL: Joi.string().default('postgresql://postgres:postgres@localhost:5432/video_saas')
});
